# Generated by Django 2.1.3 on 2018-11-24 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default='Descripción del board', max_length=200),
            preserve_default=False,
        ),
    ]
