# Generated by Django 2.1.3 on 2018-11-28 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0003_auto_20181125_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
